module.exports = {
  apps: [
    {
      name: 'mav-console',
      script: 'server.mjs',
      cwd: 'C:\\Workspace\\Active\\homelab-noc-dashboard\\homelab-noc-dashboard\\homelab-noc-dashboard',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      max_restarts: 5,
      env: { NODE_ENV: 'production', PORT: '3000' },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'prometheus-sync',
      script: 'C:\\Workspace\\Active\\homelab-noc-dashboard\\homelab-noc-dashboard\\homelab-noc-dashboard\\scripts\\prometheus-sync.mjs',
      cwd: 'C:\\Workspace\\Active\\homelab-noc-dashboard\\homelab-noc-dashboard\\homelab-noc-dashboard',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env_file: 'C:\\Workspace\\Active\\SEO-Agents-App\\.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'downloads-watcher',
      script: 'C:\\Users\\carte\\DownloadsOrganizer\\downloads_watcher.py',
      interpreter: 'C:\\Users\\carte\\DownloadsOrganizer\\.venv\\Scripts\\python.exe',
      cwd: 'C:\\Users\\carte\\DownloadsOrganizer',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mav-bridge',
      script: 'C:\\Workspace\\Active\\SEO-Agents-App\\scripts\\mav-bridge.mjs',
      cwd: 'C:\\Workspace\\Active\\SEO-Agents-App',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env_file: 'C:\\Workspace\\Active\\SEO-Agents-App\\.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ]
};
